### ISSUE TITLE
Check 3x3 square for an answer

### ISSUE THREAD

**Issue by jybluekim** [ajkim0630/Sudoku#3]
Currently you are only scanning row and column for possible answers and checking to see if there is ONE unique number that appears in both sets.

Can you extend this so you also check the 3x3 square? If you are looking at (0,0) then you should check between (0,0) and (2,2) and so on. A simple for loop should work with some if statements. 

Stating the obvious but now you will have to check THREE sets for a unique number which will give you stronger inference than looking at TWO sets only. 

Have fun!

**Comment by ajkim0630** [comment]
fixed it

**Comment by jybluekim** [comment]
@ajkim0630 , You need to upload the new code, then close it

**Comment by ajkim0630** [comment]
FINE!!! >:(
